name: google_api_headers
description: A Flutter plugin for getting the headers required to call Google APIs with an app restricted API key
version: 4.2.3
homepage: https://github.com/zeshuaro/google_api_headers

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.2

dev_dependencies:
  build_runner: 2.4.9
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: io.github.zeshuaro.google_api_headers
        pluginClass: GoogleApiHeadersPlugin
      ios:
        default_package: google_api_headers
      web:
        default_package: google_api_headers
      macos:
        default_package: google_api_headers
      windows:
        default_package: google_api_headers
      linux:
        default_package: google_api_headers
